<a href="https://colab.research.google.com/github/doney25/numpy_pandas/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a NumPy array with values from 10 to 49 (inclusive).


● Reshape it into a 4x10 matrix.


● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np

arr1=np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
matrix=arr1.reshape(4,10)
print(matrix)
print()
matrix[:, -1]

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]



array([19, 29, 39, 49])

2. Create two 3×3 matrices:


One filled with all 5s , One with values from 1 to 9


● Add the two matrices


● Multiply them element-wise


● Then find the transpose of the result


In [ ]:
A=np.array([[5,5,5],
           [5,5,5],
           [5,5,5]])
B=np.arange(1,10).reshape(3,3)
print(f"A+B:\n{A+B}\n")
result=A*B
print(f"A*B:\n{result}\n")
matrix_trans=result.T
print(f"Transporse matrix:\n{matrix_trans}")

A+B:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

A*B:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transporse matrix:
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


Create a NumPy array of 15 random integers between 10 and 100.

● Replace all values greater than 50 with -1

● Count how many values were replaced.

In [ ]:
A=np.random.randint(10,101,15)
print(f"Original random array: {A}")

total=np.sum(A>50)

A[A>50]=-1

print(f"Replaced array: {A}")
print(f"Count of replaced numbers: {total}")


Original random array: [ 70  62  52  65  83  70  23  84 100  53  71  59  11  37  44]
Replaced array: [-1 -1 -1 -1 -1 -1 23 -1 -1 -1 -1 -1 11 37 44]
Count of replaced numbers: 11


4. Generate a 5×4 array with random values between 0 and 1 (float).


● Find the row with the maximum sum of values.


● Normalize each row using the formula: x-min/max-min

In [ ]:
arr=np.random.rand(5,4)
print(arr)

row_sum=np.sum(arr,axis=1)
print(f"\nSum of rows: {row_sum}")

print(f"Row with max sum: {arr[np.argmax(row_sum)]}")

row_min=np.min(arr,axis=1,keepdims=True)
row_max=np.max(arr,axis=1,keepdims=True)
normalize=(arr-row_min)/(row_max-row_min)
print(f"\nNormalized:\n {normalize}")

[[0.46060854 0.03620092 0.89487099 0.48148047]
 [0.92437026 0.45255448 0.85221374 0.94295315]
 [0.45401657 0.87256709 0.11099381 0.31624883]
 [0.54325248 0.05727717 0.49695305 0.03611966]
 [0.94386878 0.15224788 0.76403187 0.9507779 ]]

Sum of rows: [1.87316092 3.17209163 1.7538263  1.13360236 2.81092643]
Row with max sum: [0.92437026 0.45255448 0.85221374 0.94295315]

Normalized:
 [[0.49426158 0.         1.         0.51856884]
 [0.96210657 0.         0.81496807 1.        ]
 [0.45041334 1.         0.         0.26951448]
 [1.         0.04171986 0.90870355 0.        ]
 [0.99134769 0.         0.76613775 1.        ]]


5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])


● Find all unique elements


● Find the duplicates (elements that appear more than once)

In [ ]:
arr=np.array([1,3,5,3,7,9,1,5,5])
print(f"Unique elements: {np.unique(arr)}")

values,count=np.unique(arr,return_counts=True)
duplicates=values[count>1]
print(f"Duplicate elements: {duplicates}")


Unique elements: [1 3 5 7 9]
Duplicate elements: [1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.<br>
● Extract the middle 4×4 submatrix.<br>
● Then extract all even numbers from this submatrix.

In [ ]:
arr=np.arange(1,37).reshape(6,6)
print(arr)
print()

submatrix=arr[1:5,1:5]
print(submatrix)
print()

even_nums=submatrix[submatrix%2==0]
print(even_nums)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

[ 8 10 14 16 20 22 26 28]


7. Generate an array of shape (3, 4) with values from 0 to 11.


● Reshape it to (2, 6)


● Then flatten it into a 1D array


● Convert the 1D array back to shape (4, 3)

In [ ]:
arr=np.arange(0,12).reshape(3,4)
print(f"Original array:\n {arr}")

print("\nReshaped array")
reshaped_array=arr.reshape(2,6)
print(reshaped_array)

print("\nFlatten 1D array")
flatten_array=reshaped_array.flatten()
print(flatten_array)

print("\n4 X 3 matrix")
print(flatten_array.reshape(4,3))

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flatten 1D array
[ 0  1  2  3  4  5  6  7  8  9 10 11]

4 X 3 matrix
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8 . Create an array: a = np.array([[1, 2], [3, 4]])


● Append a new row [5, 6]


● Then append a new column [7, 8, 9]

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)

A=np.vstack((A,[5,6]))
print("\nAppending new row: ")
print(A)

print("\nAppending new column: ")
A=np.hstack((A,[[7],[8],[9]]))
print(A)

[[1 2]
 [3 4]]

Appending new row: 
[[1 2]
 [3 4]
 [5 6]]

Appending new column: 
[[1 2 7]
 [3 4 8]
 [5 6 9]]


9.

a = np.array([1, 2, 3]) <br>
b = np.array([4, 5, 6])<br>
c = np.array([7, 8, 9])<br>
● Join them into a single array<br>
● Reshape the result into a 3×3 matrix<br>
● Extract the diagonal elements


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined_array=np.concatenate((a,b,c))
print("Single Array:")
print(joined_array)

reshaped_array=joined_array.reshape(3,3)
print("\nReshaped Array:")
print(reshaped_array)

print("\nDiagonal elements:")
print(np.diag(reshaped_array))

Single Array:
[1 2 3 4 5 6 7 8 9]

Reshaped Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements:
[1 5 9]


10. Create a NumPy array of integers from 1 to 20.

● Extract all values that are divisible by 3 or 5.


● Count how many such values exist.

In [ ]:
arr=np.arange(1,21)

new_array=arr[(arr%3==0) | (arr%5==0)]
print("Values disvisble by 3 or 5:")
print(new_array)
print(f"\nCount: {len(new_array)}")


Values disvisble by 3 or 5:
[ 3  5  6  9 10 12 15 18 20]

Count: 9
